package com.example.bookstoreapi4.controller;

import com.example.bookstoreapi4.model.Customer;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/customers")
public class CustomerController {

    @PostMapping("/register")
    public ResponseEntity<Customer> registerCustomer(@RequestBody Customer customer) {
        // Simulate saving the customer to the database
        customer.setId(1L);  // Normally, this would be generated by the database
        return new ResponseEntity<>(customer, HttpStatus.CREATED);
    }
}
